### ISSUE TITLE
as a provider I want to search for requests and offers by title or user so that I can resolve requester’s problems

### ISSUE THREAD

**Issue by thedanzjl** [darkTeaLeaf/cross_service#10]
Given a feed, a dropdown list of search options
When I fill the field, choose searching "by user" or "by title" and press "search"
Then I can see the feed filtered by the item I required

**Comment by caffeinatedgaze** [comment]
- [x] Add a dropdown list
- [x] Implement logic

**Comment by caffeinatedgaze** [comment]
Create nice drop down that will provide the scope for advanced search and sorting. Consult bootstrap examples
