### ISSUE TITLE
as a user I want to manage my personal information so that I can keep the information up-to-date

### ISSUE THREAD

**Issue by thedanzjl** [darkTeaLeaf/cross_service#4]
**Account management [3]**  
Given user's account page
When I press "edit" button and rewrite some fields with new data and press "submit"
Then everybody can see the changes

- [x] add additional fields
- [x] change password
- [x] watch other user's information

- [ ] add "make sure" and other alerts

- [x] add list of requests & offers of the user

- [x] add avatar

#sprint2

**Comment by thedownhill** [comment]
add additional fields
